#!/bin/bash

set -e
set -x

thrift -strict \
       -recurse \
      --gen go:package_prefix="gen-go/" \
      -o "go-server/src" \
      "thrift-defs/guitars.thrift"

find go-server/src/gen-go -name '*.go' | xargs gofmt -w
