#!/bin/bash

# set -x
set -e

server_cmd=go-server/bin/go-service
client_cmd="go-server/bin/guitars-remote -P binary -framed -h localhost:9090"

$server_cmd &
server_pid=${!}

function on_exit {
  echo "Stopping the service"
  kill $server_pid
}
trap on_exit EXIT

sleep 1

$client_cmd create "Charvel" "San Dimas"
$client_cmd create "Fender" "Telecaster"
$client_cmd create "Fender" "Stratocaster"
$client_cmd create "Fender" "Jaguar"
$client_cmd create "Gibson" "Les Paul"
$client_cmd create "Gibson" "SG"
$client_cmd all
